import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Provider from './provider';
import { Nunito } from 'next/font/google';
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton,
} from '@clerk/nextjs';

const myFont = Nunito({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
